# Generated by Django 5.2.7 on 2025-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(blank=True, choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart')], max_length=20, null=True),
        ),
    ]
